trigger:
- master

variables:
  - name: agent.preferPowerShellOnContainers
    value: 'True'

stages:
  - stage: Build
    displayName:  Create build artifact
    jobs:
      - job: BuildArtifact

        pool:
          vmImage: 'windows-latest'

        container:
          image: uipathcontainerreg.azurecr.io/uipathrobot:18
          endpoint: UiPathContainerReg

        steps:
          - script: C:\UiPath\\UiRobot.exe pack $(Build.SourcesDirectory)\project.json -o $(Build.ArtifactStagingDirectory)\ -v 1.0.$(Build.BuildId)
            displayName: 'Build Artifact'
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: drop
        
  - stage: DeployUAT
    displayName:  Deploy build artifact to UAT
    dependsOn:  Build
    condition:  succeeded()
    jobs:
      - deployment:  deployUAT
        displayName:  Deploy package to UAT Orchestrator
        container:
          image: uipathcontainerreg.azurecr.io/uipathrobot:18
          endpoint: UiPathContainerReg
        pool:
          vmImage: 'windows-latest'
        environment:  UAT
        strategy:
          runOnce:
              deploy:
                steps:
                  - download: current
                    artifact: drop
                    displayName: Download artifact on build agent
                  - powershell: |
                      Import-Module UiPath.Powershell
                      $token = Get-UiPathAuthToken -ClientId $(uatClientID) -UserKey $(uatUserKey) -AccountName 'Vijayffskoti' -CloudDeployment 'Production' -TenantName 'VijaykumarDkv9699751'
                      Add-UiPathPackage -PackageFile $(Pipeline.Workspace)\drop\HelloWorld.1.0.$(Build.BuildId).nupkg -AuthToken $token

  - stage: DeployProd
    displayName:  Deploy build artifact to PROD
    dependsOn:  DeployUAT
    condition:  succeeded()
    jobs:
      - deployment:  deployProd
        displayName:  Deploy package to PROD Orchestrator
        container:
          image: uipathcontainerreg.azurecr.io/uipathrobot:18
          endpoint: UiPathContainerReg
        pool:
          vmImage: 'windows-latest'
        environment:  PROD
        strategy:
          runOnce:
              deploy:
                steps:
                  - download: current
                    artifact: drop
                    displayName: Download artifact on build agent
                  - powershell: |
                      Import-Module UiPath.Powershell
                      $token = Get-UiPathAuthToken -ClientId $(prodClientID) -UserKey $(prodUserKey) -AccountName 'myorctenancy'  -CloudDeployment 'Production' -TenantName 'myorctenancy' 
                      Add-UiPathPackage -PackageFile $(Pipeline.Workspace)\drop\HelloWorld.1.0.$(Build.BuildId).nupkg -AuthToken $token