trigger:
- master

variables:
- name: agent.preferPowerShellOnContainers
  value: 'True'

pool:
  vmImage: 'windows-latest'

container:
  image: uipathcontainerreg.azurecr.io/uipathrobot:16
  endpoint: UiPathContainerReg

steps:
- script: C:\UiPath\\UiRobot.exe pack $(Build.SourcesDirectory)\project.json -o $(Build.ArtifactStagingDirectory)\ -v 1.0.$(Build.BuildId)
  displayName: 'Build Artifact'
- publish: $(Build.ArtifactStagingDirectory)
  artifact: drop